#!/bin/bash

# Planning Model Configuration Demo Script
# This script demonstrates the new separate planning model configuration feature

echo "=== OpenAI Reasoning Model Planning Demo ==="
echo ""
echo "This demo showcases the new planning model configuration that allows"
echo "the agent to use specialized OpenAI reasoning models (o1, o3, etc.)"
echo "for planning tasks while using a different model for conversation."
echo ""

echo "=== Key Features ==="
echo ""
echo "✓ Separate Model Configuration"
echo "  - Conversation Model: For iterative conversation and general tasks"
echo "  - Planning Model: For complex reasoning and task planning"
echo ""

echo "✓ OpenAI Reasoning Model Support"
echo "  - o1: Advanced reasoning for complex planning scenarios"
echo "  - o1-mini: Faster reasoning for simpler planning tasks"  
echo "  - o1-preview: Preview version of o1 reasoning model"
echo "  - o3: Latest reasoning model for sophisticated analysis"
echo "  - o3-mini: Efficient version of o3 for routine planning"
echo ""

echo "✓ Environment Variable Configuration"
echo "  - AGENT_MODEL: Sets the conversation model"
echo "  - PLANNING_MODEL: Sets the planning model"
echo ""

echo "=== Configuration Examples ==="
echo ""
echo "# Use GPT-4.1 for conversation and o1-preview for planning"
echo "export AGENT_MODEL=\"gpt-4.1\""
echo "export PLANNING_MODEL=\"o1-preview\""
echo ""

echo "# Use o3 for advanced reasoning in planning"
echo "export AGENT_MODEL=\"gpt-4.1\""
echo "export PLANNING_MODEL=\"o3\""
echo ""

echo "# Use the same model for both (fallback behavior)"
echo "export AGENT_MODEL=\"gpt-4.1\""
echo "# PLANNING_MODEL not set - will use AGENT_MODEL"
echo ""

echo "=== Code Usage Example ==="
echo ""
echo "// Configure separate models in C#"
echo "var config = new AgentConfiguration"
echo "{"
echo "    Model = \"gpt-4.1\",              // For conversation"
echo "    PlanningModel = \"o1-preview\"    // For planning"
echo "};"
echo ""
echo "var planningService = new PlanningService(config, openAiService, logger);"
echo "var plan = await planningService.CreatePlanAsync(\"Analyze Q4 sales data\");"
echo ""

echo "=== Benefits ==="
echo ""
echo "🧠 Enhanced Planning Intelligence"
echo "   - Reasoning models excel at complex task breakdown"
echo "   - Better tool selection and orchestration"
echo "   - More sophisticated execution strategies"
echo ""

echo "💰 Cost Optimization"
echo "   - Use expensive reasoning models only for planning"
echo "   - Cheaper models for routine conversation"
echo "   - Optimal resource allocation"
echo ""

echo "⚡ Performance Optimization"
echo "   - Fast conversation models for real-time interaction"
echo "   - Powerful reasoning models for complex planning"
echo "   - Best of both worlds"
echo ""

echo "🎯 Specialized Capabilities"
echo "   - Leverage model strengths for specific tasks"
echo "   - Planning optimized for reasoning and analysis"
echo "   - Conversation optimized for interaction"
echo ""

echo "=== Implementation Status ==="
echo ""
echo "✅ AgentConfiguration with PlanningModel property"
echo "✅ Environment variable support (PLANNING_MODEL)"
echo "✅ Model validation for OpenAI reasoning models"
echo "✅ PlanningService using configurable models"
echo "✅ Dependency injection registration"
echo "✅ Comprehensive test coverage"
echo "✅ Updated documentation and examples"
echo ""

echo "The planning system now intelligently separates conversation and planning"
echo "responsibilities, enabling optimal use of specialized models for each task type."
echo ""
echo "=== Demo Complete ==="