namespace Common.Models.Session;

/// <summary>
/// Represents a comprehensive session summary generated by the LLM
/// </summary>
public class SessionSummary
{
    /// <summary>
    /// The session this summary belongs to
    /// </summary>
    public string SessionId { get; set; } = string.Empty;
    
    /// <summary>
    /// Session name
    /// </summary>
    public string SessionName { get; set; } = string.Empty;
    
    /// <summary>
    /// When the summary was generated
    /// </summary>
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// Session start time
    /// </summary>
    public DateTime SessionStartTime { get; set; }
    
    /// <summary>
    /// Session end time (if completed)
    /// </summary>
    public DateTime? SessionEndTime { get; set; }
    
    /// <summary>
    /// Total session duration
    /// </summary>
    public TimeSpan? Duration => SessionEndTime?.Subtract(SessionStartTime);
    
    /// <summary>
    /// Overall session status
    /// </summary>
    public SessionStatus Status { get; set; }
    
    /// <summary>
    /// Complete markdown summary document
    /// </summary>
    public string MarkdownSummary { get; set; } = string.Empty;
    
    /// <summary>
    /// Executive summary (brief overview)
    /// </summary>
    public string ExecutiveSummary { get; set; } = string.Empty;
    
    /// <summary>
    /// Task completion assessment
    /// </summary>
    public TaskCompletionAssessment TaskCompletion { get; set; } = new();
    
    /// <summary>
    /// Summary statistics
    /// </summary>
    public SessionStatistics Statistics { get; set; } = new();
    
    /// <summary>
    /// Key errors encountered during the session
    /// </summary>
    public List<ErrorSummary> Errors { get; set; } = new();
    
    /// <summary>
    /// Options used to generate this summary
    /// </summary>
    public string SummaryOptionsSnapshot { get; set; } = string.Empty;
}

/// <summary>
/// Assessment of task completion
/// </summary>
public class TaskCompletionAssessment
{
    /// <summary>
    /// Whether the primary task was completed
    /// </summary>
    public bool TaskCompleted { get; set; }
    
    /// <summary>
    /// Percentage of completion (0-100)
    /// </summary>
    public int CompletionPercentage { get; set; }
    
    /// <summary>
    /// Evidence supporting task completion
    /// </summary>
    public List<string> Evidence { get; set; } = new();
    
    /// <summary>
    /// Subtasks that were completed
    /// </summary>
    public List<string> CompletedSubtasks { get; set; } = new();
    
    /// <summary>
    /// Subtasks that failed or were not attempted
    /// </summary>
    public List<string> FailedSubtasks { get; set; } = new();
}

/// <summary>
/// Session performance and usage statistics
/// </summary>
public class SessionStatistics
{
    /// <summary>
    /// Total number of activities logged
    /// </summary>
    public int TotalActivities { get; set; }
    
    /// <summary>
    /// Number of tool calls made
    /// </summary>
    public int ToolCalls { get; set; }
    
    /// <summary>
    /// Number of successful tool calls
    /// </summary>
    public int SuccessfulToolCalls { get; set; }
    
    /// <summary>
    /// Tool call success rate (0-100)
    /// </summary>
    public double ToolCallSuccessRate => ToolCalls > 0 ? (double)SuccessfulToolCalls / ToolCalls * 100 : 0;
    
    /// <summary>
    /// Number of OpenAI API requests
    /// </summary>
    public int OpenAIRequests { get; set; }
    
    /// <summary>
    /// Number of errors encountered
    /// </summary>
    public int ErrorCount { get; set; }
    
    /// <summary>
    /// Estimated token usage
    /// </summary>
    public int EstimatedTokens { get; set; }
    
    /// <summary>
    /// Most frequently used tools
    /// </summary>
    public Dictionary<string, int> ToolUsage { get; set; } = new();
}

/// <summary>
/// Summary of an error encountered during the session
/// </summary>
public class ErrorSummary
{
    /// <summary>
    /// When the error occurred
    /// </summary>
    public DateTime Timestamp { get; set; }
    
    /// <summary>
    /// Type of error
    /// </summary>
    public string ErrorType { get; set; } = string.Empty;
    
    /// <summary>
    /// Brief description of the error
    /// </summary>
    public string Description { get; set; } = string.Empty;
    
    /// <summary>
    /// Root cause analysis
    /// </summary>
    public string RootCause { get; set; } = string.Empty;
    
    /// <summary>
    /// How the error was resolved (if applicable)
    /// </summary>
    public string Resolution { get; set; } = string.Empty;
    
    /// <summary>
    /// Impact on session progress
    /// </summary>
    public ErrorImpact Impact { get; set; }
}

/// <summary>
/// Impact level of an error on session progress
/// </summary>
public enum ErrorImpact
{
    Low,     // Minimal impact, session continued normally
    Medium,  // Some impact, workaround found
    High,    // Significant impact, task partially affected
    Critical // Critical impact, task failed or incomplete
}