apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- secrets.yaml
- mcpserver.yaml
- approval-service.yaml
- agent-alpha.yaml
- ingress.yaml

commonLabels:
  project: agents
  version: v1

namespace: agents